name: "📦🔰 Deploy slides via GitHub Pages"

on:
  push:
    branches:
    - teppichmesser
  workflow_dispatch:

jobs:
  build:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: '[Inject] Add Stylesheets'
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: |
          <link rel="stylesheet" href="/dist/theme/white.css">
        replace: |
          <!-- Qwiri Fork Start -->
          <link rel="stylesheet" id="night" href="/dist/theme/night.css">
          <link rel="stylesheet alternate" id="white" href="/dist/theme/white.css">
          <link rel="stylesheet alternate" id="moon" href="/dist/theme/moon.css">

          <script defer>
              let themes = [ 'night', 'white', 'moon' ];
              let current = 0;

              function toggleTheme() {
                current = (current + 1) % themes.length;
                for (const i in themes) {
                  if (current == i) {
                    document.getElementById(themes[i]).setAttribute("rel", "stylesheet");
                  } else {
                    document.getElementById(themes[i]).setAttribute("rel", "stylesheet alternate");
                  }
                }
              }
          </script>
          <!-- / Qwiri Fork End -->
    
    - name: '[Inject] Add Change Theme Button'
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: |
          <div class="reveal">
        replace: |
          <!-- Qwiri Fork Start -->
          <style>
          #qf-controls {
            position: absolute;
            z-index: 1;
            margin-top: .25rem;
            margin-left: .25rem;
          }
          #qf-controls button {
            background: black;
            border-radius: 0.5rem;
            padding: 0.5rem 1rem 0.5rem 1rem;
            color: white;
          }
          </style>
          
          <div id="qf-controls">
            <button onclick="window.location = '/'">Home</button>
            <button onclick="toggleTheme()">Change Theme</button>
          </div>
          <!-- / Qwiri Fork End -->
          
          <div class="reveal">
    
    - name: '[Inject] Update Repo Links'
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: 'https://gitlab.com/dhbw_webengineering_2/slides/-/'
        replace: 'https://github.com/Qwiri/WebEng2-Community-Fork/'
# 
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        cname: webeng2.d2a.io